### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by FRidh** [sphinx-doc/sphinx-testing#5]
```
======================================================================
FAIL: test_TestApp_cleanup (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/sphinx-testing-0.7.2/tests/test_util.py", line 102, in test_TestApp_cleanup
    self.assertEqual(1, Theme.themes.clear.call_count)
AssertionError: 1 != 0

======================================================================
FAIL: test_TestApp_cleanup_when_cleanup_on_errors (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/sphinx-testing-0.7.2/tests/test_util.py", line 120, in test_TestApp_cleanup_when_cleanup_on_errors
    self.assertEqual(1, Theme.themes.clear.call_count)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 39 tests in 0.598s

FAILED (failures=2)

```
With both Python 2.7 and 3.6 and Sphinx at 1.6.3.

**Comment by tk0miya** [comment]
Fixed by #7.
Thank you for reporting.
