### ISSUE TITLE
Tests are failing with Sphinx 1.8.2

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx-testing#8]
With the latest Sphinx, I get this error:
```python
ERROR: test_TestApp_when_copy_srcdir_to_tmpdir (test_util.TestSphinxTesting)

Traceback (most recent call last):
  File "/home/dmitry/upstream/sphinx-testing/tests/test_util.py", line 86, in test_TestApp_when_copy_srcdir_to_tmpdir
    (app.srcdir / 'conf.py').read_text())
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by tk0miya** [comment]
Fixed by 3b9ca63.
Thank you for reporting.

**Comment by tk0miya** [comment]
I just released sphinx-testing 0.8.0 including this.

**Comment by zorun** [comment]
I get the same kind of errors with sphinx-testing 1.0.0 and sphinx 2.0.1 (with Python 3.7):

```
EE..EE..EEEE
======================================================================
ERROR: test_TestApp_when_copy_srcdir_to_tmpdir (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 86, in test_TestApp_when_copy_srcdir_to_tmpdir
    (app.srcdir / 'conf.py').read_text())
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_TestApp_when_create_new_srcdir (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 68, in test_TestApp_when_create_new_srcdir
    self.assertEqual('', (app.srcdir / 'conf.py').read_text())
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_TestApp_when_srcdir_specified (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 51, in test_TestApp_when_srcdir_specified
    (app.srcdir / 'conf.py').read_text())
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_with_app (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 150, in test_with_app
    execute()
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 166, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 136, in execute
    (app.srcdir / 'unknown.rst').write_text('')
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_with_app_write_docstring (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 175, in test_with_app_write_docstring
    execute()
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 164, in decorator
    self.write_docstring(app, func.__doc__)
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 147, in write_docstring
    filename = app.srcdir / basename
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_with_app_write_docstring_by_name (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 204, in test_with_app_write_docstring_by_name
    execute()
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 164, in decorator
    self.write_docstring(app, func.__doc__)
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 149, in write_docstring
    filename = app.srcdir / self._write_docstring
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_with_app_write_docstring_with_master_doc (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 185, in test_with_app_write_docstring_with_master_doc
    execute()
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 164, in decorator
    self.write_docstring(app, func.__doc__)
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 147, in write_docstring
    filename = app.srcdir / basename
TypeError: unsupported operand type(s) for /: 'str' and 'str'

======================================================================
ERROR: test_with_app_write_docstring_with_source_suffix (test_util.TestSphinxTesting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/tests/test_util.py", line 195, in test_with_app_write_docstring_with_source_suffix
    execute()
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 164, in decorator
    self.write_docstring(app, func.__doc__)
  File "/build/python-sphinx-testing/src/sphinx-testing-1.0.0/src/sphinx_testing/util.py", line 147, in write_docstring
    filename = app.srcdir / basename
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by tk0miya** [comment]
Fixed again.

**Comment by zorun** [comment]
Thanks!
