### ISSUE TITLE
warningiserror=True is broken with Sphinx 1.8.2

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx-testing#9]
Thanks for fixing the previous bug (#8)! Here is another one.

If a test is using `warningiserror=True`, and it is not the first test to be run, it fails.

Consider this simple example:
```python
import unittest
from sphinx_testing import with_app

class MyTestCase(unittest.TestCase):
    @with_app(buildername='html', srcdir='docs', warningiserror=True)
    def test_pass1(self, app, status, warning):
        pass

    @with_app(buildername='html', srcdir='docs', warningiserror=True)
    def test_pass2(self, app, status, warning):
        pass

if __name__ == "__main__":
    unittest.main(verbosity=2)
```

The first test passes, but the second one fails:
```
test_pass1 (__main__.MyTestCase) ... ok
test_pass2 (__main__.MyTestCase) ... ERROR
```

The traceback is:
```python
Traceback (most recent call last):
  File "/home/dmitry/upstream/sphinx-testing/src/sphinx_testing/util.py", line 148, in decorator
    app = TestApp(*self.sphinxargs, **sphinxkwargs)
  File "/home/dmitry/upstream/sphinx-testing/src/sphinx_testing/util.py", line 87, in __init__
    verbosity, parallel)
  File "/home/dmitry/upstream/sphinx/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/home/dmitry/upstream/sphinx/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/dmitry/upstream/sphinx/sphinx/registry.py", line 483, in load_extension
    metadata = mod.setup(app)
  File "/home/dmitry/upstream/sphinx/sphinx/domains/changeset.py", line 150, in setup
    app.add_directive('deprecated', VersionChange)
  File "/home/dmitry/upstream/sphinx/sphinx/application.py", line 727, in add_directive
    type='app', subtype='add_directive')
  File "/usr/lib/python3.6/logging/__init__.py", line 1642, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/home/dmitry/upstream/sphinx/sphinx/util/logging.py", line 130, in log
    super(SphinxLoggerAdapter, self).log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1674, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 861, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 720, in filter
    result = f.filter(record)
  File "/home/dmitry/upstream/sphinx/sphinx/util/logging.py", line 412, in filter
    raise SphinxWarning(message)
sphinx.errors.SphinxWarning: while setting up extension sphinx.domains.changeset: directive 'deprecated' is already registered, it will be overridden
```

This affects other projects, see e.g. mcmtroffaes/sphinxcontrib-bibtex#149.

I am using the latest version of Sphinx from 1.8 branch and the latest version of sphinx-testing from master.

**Comment by mitya57** [comment]
P.S. I am not sure whether this is a bug in sphinx-testing or sphinx itself.

Either sphinx should not issue the warning when creating an application object twice, or sphinx-testing should filter that warning out.
